export { Navbar } from './nav/Navbar'
export { Banner } from './banner/Banner'
export { About } from './about/About'
export { Skill } from './skill/Skill'
export { Experience } from './experience/Experience'
export { Footer } from './footer/Footer'
